### ISSUE TITLE
Create demo for temperature-time-series

### ISSUE THREAD

**Issue by JimmyCIsCrazySee** [cs481-ekh/f22-dust-devils#118]

**Comment by senamihodonu** [comment]
11/4/2022
Work session 2pm-6pm
I worked on the following tasks:
- Temperature time series jupyter notebooks demo
- Size limit for read_data functions
- Time vs Temperature plots

**Comment by senamihodonu** [comment]
11/14/2022
Work session 6pm-7pm
Added demos to the Using_Muldoon and Using_Temperature_Timeseries notebooks

**Comment by senamihodonu** [comment]
Temperature demonstration incorporated into Using_Muldoon
