### ISSUE TITLE
Wind Speed Timeseries Model

### ISSUE THREAD

**Issue by senamihodonu** [cs481-ekh/f22-dust-devils#54]
As a user, given a meteorological data I want to be able to model the wind speed time series, so that I can comprehend the impact of the dust devil for that given time span on Mars surface.

## Definition of Done
- [x] Pytest should pass all related tests
- [x] When used correctly, plots should be formed when used in Jupyter Notebooks

## Tasks
- [x] #57
- [x] #58
- [x] #64
- [x] #59
- [x] #60

**Comment by samfarmer1** [comment]
This story will be moved into Sprint 4 because we have to work with our sponsor to update the Python package with the changes made in this repository, so we can then import the right package in Jupyter Notebooks to close #59 .
